name: Upload Python Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.x'

    - name: Run testcase
      id: unittest_cases
      run: |
          python -m pip install pyinstaller
          python -m unittest discover tests
        
    - name: Clean folders before moving
      run: |
        echo "Cleaning dist and build directories..."
        if (Test-Path -Path dist) { Remove-Item -Path dist -Recurse -Force }
        if (Test-Path -Path build) { Remove-Item -Path build -Recurse -Force }
      shell: pwsh

    - name: Build and publish to pypi
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
      run: |
        python -m pip install --upgrade pip
        python -m pip install setuptools
        python -m pip install twine
        python -m pip install build
        python -m build
        python -m twine upload dist/*